site_name: Demisto-SDK

theme:
    name: material
    logo: icons/logo.png

markdown_extensions:
    - mkdocs-click
    - attr_list
    - mdx_truly_sane_lists
    - toc

plugins:
    - mkdocstrings
    - autorefs
